/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.ERRORUNKNOWN
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object NewAccountApi {

  /**
   * Endpoint to add a new acount to the store
   * 
   * Expected answers:
   *   code 400 :  (Bad request, no serializer valid data for account)
   *   code 500 :  (Internal server error, for any exception when account is created)
   *   code 200 :  (Account is created)
   * 
   * @param userId The ID of the user to return
   */
  def accountsPost(userId: ERRORUNKNOWN): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/DIXMA/test_tpaga/0.0.1", "/accounts", "application/json")
      .withPathParam("userId", userId)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](500)
      .withSuccessResponse[Unit](200)
      

}

